# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Test.proto',
  package='',
  syntax='proto2',
  serialized_options=b'\n$com.janlr.ag.test.common.fixed.protoB\016testLoginProtoH\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nTest.proto\"/\n\x08\x43\x32SLogin\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x12\n\nconnectKey\x18\x02 \x01(\t\"+\n\x08S2CLogin\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\"\x1b\n\x08\x43\x32SHeart\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\"\x1b\n\x08S2CHeart\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\tB8\n$com.janlr.ag.test.common.fixed.protoB\x0etestLoginProtoH\x03'
)




_C2SLOGIN = _descriptor.Descriptor(
  name='C2SLogin',
  full_name='C2SLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='C2SLogin.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connectKey', full_name='C2SLogin.connectKey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=61,
)


_S2CLOGIN = _descriptor.Descriptor(
  name='S2CLogin',
  full_name='S2CLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='S2CLogin.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='S2CLogin.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=106,
)


_C2SHEART = _descriptor.Descriptor(
  name='C2SHeart',
  full_name='C2SHeart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='C2SHeart.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=135,
)


_S2CHEART = _descriptor.Descriptor(
  name='S2CHeart',
  full_name='S2CHeart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='S2CHeart.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['C2SLogin'] = _C2SLOGIN
DESCRIPTOR.message_types_by_name['S2CLogin'] = _S2CLOGIN
DESCRIPTOR.message_types_by_name['C2SHeart'] = _C2SHEART
DESCRIPTOR.message_types_by_name['S2CHeart'] = _S2CHEART
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C2SLogin = _reflection.GeneratedProtocolMessageType('C2SLogin', (_message.Message,), {
  'DESCRIPTOR' : _C2SLOGIN,
  '__module__' : 'Test_pb2'
  # @@protoc_insertion_point(class_scope:C2SLogin)
  })
_sym_db.RegisterMessage(C2SLogin)

S2CLogin = _reflection.GeneratedProtocolMessageType('S2CLogin', (_message.Message,), {
  'DESCRIPTOR' : _S2CLOGIN,
  '__module__' : 'Test_pb2'
  # @@protoc_insertion_point(class_scope:S2CLogin)
  })
_sym_db.RegisterMessage(S2CLogin)

C2SHeart = _reflection.GeneratedProtocolMessageType('C2SHeart', (_message.Message,), {
  'DESCRIPTOR' : _C2SHEART,
  '__module__' : 'Test_pb2'
  # @@protoc_insertion_point(class_scope:C2SHeart)
  })
_sym_db.RegisterMessage(C2SHeart)

S2CHeart = _reflection.GeneratedProtocolMessageType('S2CHeart', (_message.Message,), {
  'DESCRIPTOR' : _S2CHEART,
  '__module__' : 'Test_pb2'
  # @@protoc_insertion_point(class_scope:S2CHeart)
  })
_sym_db.RegisterMessage(S2CHeart)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
